// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: streaming_rpc_meta.proto

package com.sjt.jrpc.protocol;

public final class StreamingRpcProto {
  private StreamingRpcProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code jrpc.FrameType}
   */
  public enum FrameType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>FRAME_TYPE_UNKNOWN = 0;</code>
     */
    FRAME_TYPE_UNKNOWN(0),
    /**
     * <code>FRAME_TYPE_RST = 1;</code>
     */
    FRAME_TYPE_RST(1),
    /**
     * <code>FRAME_TYPE_CLOSE = 2;</code>
     */
    FRAME_TYPE_CLOSE(2),
    /**
     * <code>FRAME_TYPE_DATA = 3;</code>
     */
    FRAME_TYPE_DATA(3),
    /**
     * <code>FRAME_TYPE_FEEDBACK = 4;</code>
     */
    FRAME_TYPE_FEEDBACK(4),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>FRAME_TYPE_UNKNOWN = 0;</code>
     */
    public static final int FRAME_TYPE_UNKNOWN_VALUE = 0;
    /**
     * <code>FRAME_TYPE_RST = 1;</code>
     */
    public static final int FRAME_TYPE_RST_VALUE = 1;
    /**
     * <code>FRAME_TYPE_CLOSE = 2;</code>
     */
    public static final int FRAME_TYPE_CLOSE_VALUE = 2;
    /**
     * <code>FRAME_TYPE_DATA = 3;</code>
     */
    public static final int FRAME_TYPE_DATA_VALUE = 3;
    /**
     * <code>FRAME_TYPE_FEEDBACK = 4;</code>
     */
    public static final int FRAME_TYPE_FEEDBACK_VALUE = 4;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static FrameType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static FrameType forNumber(int value) {
      switch (value) {
        case 0: return FRAME_TYPE_UNKNOWN;
        case 1: return FRAME_TYPE_RST;
        case 2: return FRAME_TYPE_CLOSE;
        case 3: return FRAME_TYPE_DATA;
        case 4: return FRAME_TYPE_FEEDBACK;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<FrameType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        FrameType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<FrameType>() {
            public FrameType findValueByNumber(int number) {
              return FrameType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.sjt.jrpc.protocol.StreamingRpcProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final FrameType[] VALUES = values();

    public static FrameType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private FrameType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:jrpc.FrameType)
  }

  public interface StreamSettingsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:jrpc.StreamSettings)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 stream_id = 1;</code>
     * @return The streamId.
     */
    long getStreamId();

    /**
     * <code>bool need_feedback = 2;</code>
     * @return The needFeedback.
     */
    boolean getNeedFeedback();

    /**
     * <code>bool writable = 3;</code>
     * @return The writable.
     */
    boolean getWritable();
  }
  /**
   * Protobuf type {@code jrpc.StreamSettings}
   */
  public  static final class StreamSettings extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:jrpc.StreamSettings)
      StreamSettingsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StreamSettings.newBuilder() to construct.
    private StreamSettings(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StreamSettings() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new StreamSettings();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private StreamSettings(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              streamId_ = input.readInt64();
              break;
            }
            case 16: {

              needFeedback_ = input.readBool();
              break;
            }
            case 24: {

              writable_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sjt.jrpc.protocol.StreamingRpcProto.internal_static_jrpc_StreamSettings_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sjt.jrpc.protocol.StreamingRpcProto.internal_static_jrpc_StreamSettings_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sjt.jrpc.protocol.StreamingRpcProto.StreamSettings.class, com.sjt.jrpc.protocol.StreamingRpcProto.StreamSettings.Builder.class);
    }

    public static final int STREAM_ID_FIELD_NUMBER = 1;
    private long streamId_;
    /**
     * <code>int64 stream_id = 1;</code>
     * @return The streamId.
     */
    public long getStreamId() {
      return streamId_;
    }

    public static final int NEED_FEEDBACK_FIELD_NUMBER = 2;
    private boolean needFeedback_;
    /**
     * <code>bool need_feedback = 2;</code>
     * @return The needFeedback.
     */
    public boolean getNeedFeedback() {
      return needFeedback_;
    }

    public static final int WRITABLE_FIELD_NUMBER = 3;
    private boolean writable_;
    /**
     * <code>bool writable = 3;</code>
     * @return The writable.
     */
    public boolean getWritable() {
      return writable_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (streamId_ != 0L) {
        output.writeInt64(1, streamId_);
      }
      if (needFeedback_ != false) {
        output.writeBool(2, needFeedback_);
      }
      if (writable_ != false) {
        output.writeBool(3, writable_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (streamId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, streamId_);
      }
      if (needFeedback_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, needFeedback_);
      }
      if (writable_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, writable_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.sjt.jrpc.protocol.StreamingRpcProto.StreamSettings)) {
        return super.equals(obj);
      }
      com.sjt.jrpc.protocol.StreamingRpcProto.StreamSettings other = (com.sjt.jrpc.protocol.StreamingRpcProto.StreamSettings) obj;

      if (getStreamId()
          != other.getStreamId()) return false;
      if (getNeedFeedback()
          != other.getNeedFeedback()) return false;
      if (getWritable()
          != other.getWritable()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STREAM_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getStreamId());
      hash = (37 * hash) + NEED_FEEDBACK_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getNeedFeedback());
      hash = (37 * hash) + WRITABLE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getWritable());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.sjt.jrpc.protocol.StreamingRpcProto.StreamSettings parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sjt.jrpc.protocol.StreamingRpcProto.StreamSettings parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sjt.jrpc.protocol.StreamingRpcProto.StreamSettings parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sjt.jrpc.protocol.StreamingRpcProto.StreamSettings parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sjt.jrpc.protocol.StreamingRpcProto.StreamSettings parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sjt.jrpc.protocol.StreamingRpcProto.StreamSettings parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sjt.jrpc.protocol.StreamingRpcProto.StreamSettings parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sjt.jrpc.protocol.StreamingRpcProto.StreamSettings parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sjt.jrpc.protocol.StreamingRpcProto.StreamSettings parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.sjt.jrpc.protocol.StreamingRpcProto.StreamSettings parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sjt.jrpc.protocol.StreamingRpcProto.StreamSettings parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sjt.jrpc.protocol.StreamingRpcProto.StreamSettings parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.sjt.jrpc.protocol.StreamingRpcProto.StreamSettings prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code jrpc.StreamSettings}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:jrpc.StreamSettings)
        com.sjt.jrpc.protocol.StreamingRpcProto.StreamSettingsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sjt.jrpc.protocol.StreamingRpcProto.internal_static_jrpc_StreamSettings_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sjt.jrpc.protocol.StreamingRpcProto.internal_static_jrpc_StreamSettings_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sjt.jrpc.protocol.StreamingRpcProto.StreamSettings.class, com.sjt.jrpc.protocol.StreamingRpcProto.StreamSettings.Builder.class);
      }

      // Construct using com.sjt.jrpc.protocol.StreamingRpcProto.StreamSettings.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        streamId_ = 0L;

        needFeedback_ = false;

        writable_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sjt.jrpc.protocol.StreamingRpcProto.internal_static_jrpc_StreamSettings_descriptor;
      }

      @java.lang.Override
      public com.sjt.jrpc.protocol.StreamingRpcProto.StreamSettings getDefaultInstanceForType() {
        return com.sjt.jrpc.protocol.StreamingRpcProto.StreamSettings.getDefaultInstance();
      }

      @java.lang.Override
      public com.sjt.jrpc.protocol.StreamingRpcProto.StreamSettings build() {
        com.sjt.jrpc.protocol.StreamingRpcProto.StreamSettings result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.sjt.jrpc.protocol.StreamingRpcProto.StreamSettings buildPartial() {
        com.sjt.jrpc.protocol.StreamingRpcProto.StreamSettings result = new com.sjt.jrpc.protocol.StreamingRpcProto.StreamSettings(this);
        result.streamId_ = streamId_;
        result.needFeedback_ = needFeedback_;
        result.writable_ = writable_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sjt.jrpc.protocol.StreamingRpcProto.StreamSettings) {
          return mergeFrom((com.sjt.jrpc.protocol.StreamingRpcProto.StreamSettings)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sjt.jrpc.protocol.StreamingRpcProto.StreamSettings other) {
        if (other == com.sjt.jrpc.protocol.StreamingRpcProto.StreamSettings.getDefaultInstance()) return this;
        if (other.getStreamId() != 0L) {
          setStreamId(other.getStreamId());
        }
        if (other.getNeedFeedback() != false) {
          setNeedFeedback(other.getNeedFeedback());
        }
        if (other.getWritable() != false) {
          setWritable(other.getWritable());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sjt.jrpc.protocol.StreamingRpcProto.StreamSettings parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.sjt.jrpc.protocol.StreamingRpcProto.StreamSettings) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long streamId_ ;
      /**
       * <code>int64 stream_id = 1;</code>
       * @return The streamId.
       */
      public long getStreamId() {
        return streamId_;
      }
      /**
       * <code>int64 stream_id = 1;</code>
       * @param value The streamId to set.
       * @return This builder for chaining.
       */
      public Builder setStreamId(long value) {
        
        streamId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 stream_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStreamId() {
        
        streamId_ = 0L;
        onChanged();
        return this;
      }

      private boolean needFeedback_ ;
      /**
       * <code>bool need_feedback = 2;</code>
       * @return The needFeedback.
       */
      public boolean getNeedFeedback() {
        return needFeedback_;
      }
      /**
       * <code>bool need_feedback = 2;</code>
       * @param value The needFeedback to set.
       * @return This builder for chaining.
       */
      public Builder setNeedFeedback(boolean value) {
        
        needFeedback_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool need_feedback = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNeedFeedback() {
        
        needFeedback_ = false;
        onChanged();
        return this;
      }

      private boolean writable_ ;
      /**
       * <code>bool writable = 3;</code>
       * @return The writable.
       */
      public boolean getWritable() {
        return writable_;
      }
      /**
       * <code>bool writable = 3;</code>
       * @param value The writable to set.
       * @return This builder for chaining.
       */
      public Builder setWritable(boolean value) {
        
        writable_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool writable = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearWritable() {
        
        writable_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:jrpc.StreamSettings)
    }

    // @@protoc_insertion_point(class_scope:jrpc.StreamSettings)
    private static final com.sjt.jrpc.protocol.StreamingRpcProto.StreamSettings DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.sjt.jrpc.protocol.StreamingRpcProto.StreamSettings();
    }

    public static com.sjt.jrpc.protocol.StreamingRpcProto.StreamSettings getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StreamSettings>
        PARSER = new com.google.protobuf.AbstractParser<StreamSettings>() {
      @java.lang.Override
      public StreamSettings parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StreamSettings(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<StreamSettings> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StreamSettings> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.sjt.jrpc.protocol.StreamingRpcProto.StreamSettings getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface StreamFrameMetaOrBuilder extends
      // @@protoc_insertion_point(interface_extends:jrpc.StreamFrameMeta)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 stream_id = 1;</code>
     * @return The streamId.
     */
    long getStreamId();

    /**
     * <code>int64 source_stream_id = 2;</code>
     * @return The sourceStreamId.
     */
    long getSourceStreamId();

    /**
     * <code>.jrpc.FrameType frame_type = 3;</code>
     * @return The enum numeric value on the wire for frameType.
     */
    int getFrameTypeValue();
    /**
     * <code>.jrpc.FrameType frame_type = 3;</code>
     * @return The frameType.
     */
    com.sjt.jrpc.protocol.StreamingRpcProto.FrameType getFrameType();

    /**
     * <code>bool has_continuation = 4;</code>
     * @return The hasContinuation.
     */
    boolean getHasContinuation();

    /**
     * <code>.jrpc.Feedback feedback = 5;</code>
     * @return Whether the feedback field is set.
     */
    boolean hasFeedback();
    /**
     * <code>.jrpc.Feedback feedback = 5;</code>
     * @return The feedback.
     */
    com.sjt.jrpc.protocol.StreamingRpcProto.Feedback getFeedback();
    /**
     * <code>.jrpc.Feedback feedback = 5;</code>
     */
    com.sjt.jrpc.protocol.StreamingRpcProto.FeedbackOrBuilder getFeedbackOrBuilder();
  }
  /**
   * Protobuf type {@code jrpc.StreamFrameMeta}
   */
  public  static final class StreamFrameMeta extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:jrpc.StreamFrameMeta)
      StreamFrameMetaOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StreamFrameMeta.newBuilder() to construct.
    private StreamFrameMeta(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StreamFrameMeta() {
      frameType_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new StreamFrameMeta();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private StreamFrameMeta(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              streamId_ = input.readInt64();
              break;
            }
            case 16: {

              sourceStreamId_ = input.readInt64();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              frameType_ = rawValue;
              break;
            }
            case 32: {

              hasContinuation_ = input.readBool();
              break;
            }
            case 42: {
              com.sjt.jrpc.protocol.StreamingRpcProto.Feedback.Builder subBuilder = null;
              if (feedback_ != null) {
                subBuilder = feedback_.toBuilder();
              }
              feedback_ = input.readMessage(com.sjt.jrpc.protocol.StreamingRpcProto.Feedback.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(feedback_);
                feedback_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sjt.jrpc.protocol.StreamingRpcProto.internal_static_jrpc_StreamFrameMeta_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sjt.jrpc.protocol.StreamingRpcProto.internal_static_jrpc_StreamFrameMeta_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sjt.jrpc.protocol.StreamingRpcProto.StreamFrameMeta.class, com.sjt.jrpc.protocol.StreamingRpcProto.StreamFrameMeta.Builder.class);
    }

    public static final int STREAM_ID_FIELD_NUMBER = 1;
    private long streamId_;
    /**
     * <code>int64 stream_id = 1;</code>
     * @return The streamId.
     */
    public long getStreamId() {
      return streamId_;
    }

    public static final int SOURCE_STREAM_ID_FIELD_NUMBER = 2;
    private long sourceStreamId_;
    /**
     * <code>int64 source_stream_id = 2;</code>
     * @return The sourceStreamId.
     */
    public long getSourceStreamId() {
      return sourceStreamId_;
    }

    public static final int FRAME_TYPE_FIELD_NUMBER = 3;
    private int frameType_;
    /**
     * <code>.jrpc.FrameType frame_type = 3;</code>
     * @return The enum numeric value on the wire for frameType.
     */
    public int getFrameTypeValue() {
      return frameType_;
    }
    /**
     * <code>.jrpc.FrameType frame_type = 3;</code>
     * @return The frameType.
     */
    public com.sjt.jrpc.protocol.StreamingRpcProto.FrameType getFrameType() {
      @SuppressWarnings("deprecation")
      com.sjt.jrpc.protocol.StreamingRpcProto.FrameType result = com.sjt.jrpc.protocol.StreamingRpcProto.FrameType.valueOf(frameType_);
      return result == null ? com.sjt.jrpc.protocol.StreamingRpcProto.FrameType.UNRECOGNIZED : result;
    }

    public static final int HAS_CONTINUATION_FIELD_NUMBER = 4;
    private boolean hasContinuation_;
    /**
     * <code>bool has_continuation = 4;</code>
     * @return The hasContinuation.
     */
    public boolean getHasContinuation() {
      return hasContinuation_;
    }

    public static final int FEEDBACK_FIELD_NUMBER = 5;
    private com.sjt.jrpc.protocol.StreamingRpcProto.Feedback feedback_;
    /**
     * <code>.jrpc.Feedback feedback = 5;</code>
     * @return Whether the feedback field is set.
     */
    public boolean hasFeedback() {
      return feedback_ != null;
    }
    /**
     * <code>.jrpc.Feedback feedback = 5;</code>
     * @return The feedback.
     */
    public com.sjt.jrpc.protocol.StreamingRpcProto.Feedback getFeedback() {
      return feedback_ == null ? com.sjt.jrpc.protocol.StreamingRpcProto.Feedback.getDefaultInstance() : feedback_;
    }
    /**
     * <code>.jrpc.Feedback feedback = 5;</code>
     */
    public com.sjt.jrpc.protocol.StreamingRpcProto.FeedbackOrBuilder getFeedbackOrBuilder() {
      return getFeedback();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (streamId_ != 0L) {
        output.writeInt64(1, streamId_);
      }
      if (sourceStreamId_ != 0L) {
        output.writeInt64(2, sourceStreamId_);
      }
      if (frameType_ != com.sjt.jrpc.protocol.StreamingRpcProto.FrameType.FRAME_TYPE_UNKNOWN.getNumber()) {
        output.writeEnum(3, frameType_);
      }
      if (hasContinuation_ != false) {
        output.writeBool(4, hasContinuation_);
      }
      if (feedback_ != null) {
        output.writeMessage(5, getFeedback());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (streamId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, streamId_);
      }
      if (sourceStreamId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, sourceStreamId_);
      }
      if (frameType_ != com.sjt.jrpc.protocol.StreamingRpcProto.FrameType.FRAME_TYPE_UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, frameType_);
      }
      if (hasContinuation_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, hasContinuation_);
      }
      if (feedback_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getFeedback());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.sjt.jrpc.protocol.StreamingRpcProto.StreamFrameMeta)) {
        return super.equals(obj);
      }
      com.sjt.jrpc.protocol.StreamingRpcProto.StreamFrameMeta other = (com.sjt.jrpc.protocol.StreamingRpcProto.StreamFrameMeta) obj;

      if (getStreamId()
          != other.getStreamId()) return false;
      if (getSourceStreamId()
          != other.getSourceStreamId()) return false;
      if (frameType_ != other.frameType_) return false;
      if (getHasContinuation()
          != other.getHasContinuation()) return false;
      if (hasFeedback() != other.hasFeedback()) return false;
      if (hasFeedback()) {
        if (!getFeedback()
            .equals(other.getFeedback())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STREAM_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getStreamId());
      hash = (37 * hash) + SOURCE_STREAM_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSourceStreamId());
      hash = (37 * hash) + FRAME_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + frameType_;
      hash = (37 * hash) + HAS_CONTINUATION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getHasContinuation());
      if (hasFeedback()) {
        hash = (37 * hash) + FEEDBACK_FIELD_NUMBER;
        hash = (53 * hash) + getFeedback().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.sjt.jrpc.protocol.StreamingRpcProto.StreamFrameMeta parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sjt.jrpc.protocol.StreamingRpcProto.StreamFrameMeta parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sjt.jrpc.protocol.StreamingRpcProto.StreamFrameMeta parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sjt.jrpc.protocol.StreamingRpcProto.StreamFrameMeta parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sjt.jrpc.protocol.StreamingRpcProto.StreamFrameMeta parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sjt.jrpc.protocol.StreamingRpcProto.StreamFrameMeta parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sjt.jrpc.protocol.StreamingRpcProto.StreamFrameMeta parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sjt.jrpc.protocol.StreamingRpcProto.StreamFrameMeta parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sjt.jrpc.protocol.StreamingRpcProto.StreamFrameMeta parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.sjt.jrpc.protocol.StreamingRpcProto.StreamFrameMeta parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sjt.jrpc.protocol.StreamingRpcProto.StreamFrameMeta parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sjt.jrpc.protocol.StreamingRpcProto.StreamFrameMeta parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.sjt.jrpc.protocol.StreamingRpcProto.StreamFrameMeta prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code jrpc.StreamFrameMeta}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:jrpc.StreamFrameMeta)
        com.sjt.jrpc.protocol.StreamingRpcProto.StreamFrameMetaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sjt.jrpc.protocol.StreamingRpcProto.internal_static_jrpc_StreamFrameMeta_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sjt.jrpc.protocol.StreamingRpcProto.internal_static_jrpc_StreamFrameMeta_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sjt.jrpc.protocol.StreamingRpcProto.StreamFrameMeta.class, com.sjt.jrpc.protocol.StreamingRpcProto.StreamFrameMeta.Builder.class);
      }

      // Construct using com.sjt.jrpc.protocol.StreamingRpcProto.StreamFrameMeta.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        streamId_ = 0L;

        sourceStreamId_ = 0L;

        frameType_ = 0;

        hasContinuation_ = false;

        if (feedbackBuilder_ == null) {
          feedback_ = null;
        } else {
          feedback_ = null;
          feedbackBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sjt.jrpc.protocol.StreamingRpcProto.internal_static_jrpc_StreamFrameMeta_descriptor;
      }

      @java.lang.Override
      public com.sjt.jrpc.protocol.StreamingRpcProto.StreamFrameMeta getDefaultInstanceForType() {
        return com.sjt.jrpc.protocol.StreamingRpcProto.StreamFrameMeta.getDefaultInstance();
      }

      @java.lang.Override
      public com.sjt.jrpc.protocol.StreamingRpcProto.StreamFrameMeta build() {
        com.sjt.jrpc.protocol.StreamingRpcProto.StreamFrameMeta result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.sjt.jrpc.protocol.StreamingRpcProto.StreamFrameMeta buildPartial() {
        com.sjt.jrpc.protocol.StreamingRpcProto.StreamFrameMeta result = new com.sjt.jrpc.protocol.StreamingRpcProto.StreamFrameMeta(this);
        result.streamId_ = streamId_;
        result.sourceStreamId_ = sourceStreamId_;
        result.frameType_ = frameType_;
        result.hasContinuation_ = hasContinuation_;
        if (feedbackBuilder_ == null) {
          result.feedback_ = feedback_;
        } else {
          result.feedback_ = feedbackBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sjt.jrpc.protocol.StreamingRpcProto.StreamFrameMeta) {
          return mergeFrom((com.sjt.jrpc.protocol.StreamingRpcProto.StreamFrameMeta)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sjt.jrpc.protocol.StreamingRpcProto.StreamFrameMeta other) {
        if (other == com.sjt.jrpc.protocol.StreamingRpcProto.StreamFrameMeta.getDefaultInstance()) return this;
        if (other.getStreamId() != 0L) {
          setStreamId(other.getStreamId());
        }
        if (other.getSourceStreamId() != 0L) {
          setSourceStreamId(other.getSourceStreamId());
        }
        if (other.frameType_ != 0) {
          setFrameTypeValue(other.getFrameTypeValue());
        }
        if (other.getHasContinuation() != false) {
          setHasContinuation(other.getHasContinuation());
        }
        if (other.hasFeedback()) {
          mergeFeedback(other.getFeedback());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sjt.jrpc.protocol.StreamingRpcProto.StreamFrameMeta parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.sjt.jrpc.protocol.StreamingRpcProto.StreamFrameMeta) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long streamId_ ;
      /**
       * <code>int64 stream_id = 1;</code>
       * @return The streamId.
       */
      public long getStreamId() {
        return streamId_;
      }
      /**
       * <code>int64 stream_id = 1;</code>
       * @param value The streamId to set.
       * @return This builder for chaining.
       */
      public Builder setStreamId(long value) {
        
        streamId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 stream_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStreamId() {
        
        streamId_ = 0L;
        onChanged();
        return this;
      }

      private long sourceStreamId_ ;
      /**
       * <code>int64 source_stream_id = 2;</code>
       * @return The sourceStreamId.
       */
      public long getSourceStreamId() {
        return sourceStreamId_;
      }
      /**
       * <code>int64 source_stream_id = 2;</code>
       * @param value The sourceStreamId to set.
       * @return This builder for chaining.
       */
      public Builder setSourceStreamId(long value) {
        
        sourceStreamId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 source_stream_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSourceStreamId() {
        
        sourceStreamId_ = 0L;
        onChanged();
        return this;
      }

      private int frameType_ = 0;
      /**
       * <code>.jrpc.FrameType frame_type = 3;</code>
       * @return The enum numeric value on the wire for frameType.
       */
      public int getFrameTypeValue() {
        return frameType_;
      }
      /**
       * <code>.jrpc.FrameType frame_type = 3;</code>
       * @param value The enum numeric value on the wire for frameType to set.
       * @return This builder for chaining.
       */
      public Builder setFrameTypeValue(int value) {
        frameType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.jrpc.FrameType frame_type = 3;</code>
       * @return The frameType.
       */
      public com.sjt.jrpc.protocol.StreamingRpcProto.FrameType getFrameType() {
        @SuppressWarnings("deprecation")
        com.sjt.jrpc.protocol.StreamingRpcProto.FrameType result = com.sjt.jrpc.protocol.StreamingRpcProto.FrameType.valueOf(frameType_);
        return result == null ? com.sjt.jrpc.protocol.StreamingRpcProto.FrameType.UNRECOGNIZED : result;
      }
      /**
       * <code>.jrpc.FrameType frame_type = 3;</code>
       * @param value The frameType to set.
       * @return This builder for chaining.
       */
      public Builder setFrameType(com.sjt.jrpc.protocol.StreamingRpcProto.FrameType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        frameType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.jrpc.FrameType frame_type = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearFrameType() {
        
        frameType_ = 0;
        onChanged();
        return this;
      }

      private boolean hasContinuation_ ;
      /**
       * <code>bool has_continuation = 4;</code>
       * @return The hasContinuation.
       */
      public boolean getHasContinuation() {
        return hasContinuation_;
      }
      /**
       * <code>bool has_continuation = 4;</code>
       * @param value The hasContinuation to set.
       * @return This builder for chaining.
       */
      public Builder setHasContinuation(boolean value) {
        
        hasContinuation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool has_continuation = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearHasContinuation() {
        
        hasContinuation_ = false;
        onChanged();
        return this;
      }

      private com.sjt.jrpc.protocol.StreamingRpcProto.Feedback feedback_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.sjt.jrpc.protocol.StreamingRpcProto.Feedback, com.sjt.jrpc.protocol.StreamingRpcProto.Feedback.Builder, com.sjt.jrpc.protocol.StreamingRpcProto.FeedbackOrBuilder> feedbackBuilder_;
      /**
       * <code>.jrpc.Feedback feedback = 5;</code>
       * @return Whether the feedback field is set.
       */
      public boolean hasFeedback() {
        return feedbackBuilder_ != null || feedback_ != null;
      }
      /**
       * <code>.jrpc.Feedback feedback = 5;</code>
       * @return The feedback.
       */
      public com.sjt.jrpc.protocol.StreamingRpcProto.Feedback getFeedback() {
        if (feedbackBuilder_ == null) {
          return feedback_ == null ? com.sjt.jrpc.protocol.StreamingRpcProto.Feedback.getDefaultInstance() : feedback_;
        } else {
          return feedbackBuilder_.getMessage();
        }
      }
      /**
       * <code>.jrpc.Feedback feedback = 5;</code>
       */
      public Builder setFeedback(com.sjt.jrpc.protocol.StreamingRpcProto.Feedback value) {
        if (feedbackBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          feedback_ = value;
          onChanged();
        } else {
          feedbackBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.jrpc.Feedback feedback = 5;</code>
       */
      public Builder setFeedback(
          com.sjt.jrpc.protocol.StreamingRpcProto.Feedback.Builder builderForValue) {
        if (feedbackBuilder_ == null) {
          feedback_ = builderForValue.build();
          onChanged();
        } else {
          feedbackBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.jrpc.Feedback feedback = 5;</code>
       */
      public Builder mergeFeedback(com.sjt.jrpc.protocol.StreamingRpcProto.Feedback value) {
        if (feedbackBuilder_ == null) {
          if (feedback_ != null) {
            feedback_ =
              com.sjt.jrpc.protocol.StreamingRpcProto.Feedback.newBuilder(feedback_).mergeFrom(value).buildPartial();
          } else {
            feedback_ = value;
          }
          onChanged();
        } else {
          feedbackBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.jrpc.Feedback feedback = 5;</code>
       */
      public Builder clearFeedback() {
        if (feedbackBuilder_ == null) {
          feedback_ = null;
          onChanged();
        } else {
          feedback_ = null;
          feedbackBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.jrpc.Feedback feedback = 5;</code>
       */
      public com.sjt.jrpc.protocol.StreamingRpcProto.Feedback.Builder getFeedbackBuilder() {
        
        onChanged();
        return getFeedbackFieldBuilder().getBuilder();
      }
      /**
       * <code>.jrpc.Feedback feedback = 5;</code>
       */
      public com.sjt.jrpc.protocol.StreamingRpcProto.FeedbackOrBuilder getFeedbackOrBuilder() {
        if (feedbackBuilder_ != null) {
          return feedbackBuilder_.getMessageOrBuilder();
        } else {
          return feedback_ == null ?
              com.sjt.jrpc.protocol.StreamingRpcProto.Feedback.getDefaultInstance() : feedback_;
        }
      }
      /**
       * <code>.jrpc.Feedback feedback = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.sjt.jrpc.protocol.StreamingRpcProto.Feedback, com.sjt.jrpc.protocol.StreamingRpcProto.Feedback.Builder, com.sjt.jrpc.protocol.StreamingRpcProto.FeedbackOrBuilder> 
          getFeedbackFieldBuilder() {
        if (feedbackBuilder_ == null) {
          feedbackBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.sjt.jrpc.protocol.StreamingRpcProto.Feedback, com.sjt.jrpc.protocol.StreamingRpcProto.Feedback.Builder, com.sjt.jrpc.protocol.StreamingRpcProto.FeedbackOrBuilder>(
                  getFeedback(),
                  getParentForChildren(),
                  isClean());
          feedback_ = null;
        }
        return feedbackBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:jrpc.StreamFrameMeta)
    }

    // @@protoc_insertion_point(class_scope:jrpc.StreamFrameMeta)
    private static final com.sjt.jrpc.protocol.StreamingRpcProto.StreamFrameMeta DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.sjt.jrpc.protocol.StreamingRpcProto.StreamFrameMeta();
    }

    public static com.sjt.jrpc.protocol.StreamingRpcProto.StreamFrameMeta getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StreamFrameMeta>
        PARSER = new com.google.protobuf.AbstractParser<StreamFrameMeta>() {
      @java.lang.Override
      public StreamFrameMeta parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StreamFrameMeta(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<StreamFrameMeta> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StreamFrameMeta> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.sjt.jrpc.protocol.StreamingRpcProto.StreamFrameMeta getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FeedbackOrBuilder extends
      // @@protoc_insertion_point(interface_extends:jrpc.Feedback)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 consumed_size = 1;</code>
     * @return The consumedSize.
     */
    long getConsumedSize();
  }
  /**
   * Protobuf type {@code jrpc.Feedback}
   */
  public  static final class Feedback extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:jrpc.Feedback)
      FeedbackOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Feedback.newBuilder() to construct.
    private Feedback(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Feedback() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Feedback();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Feedback(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              consumedSize_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sjt.jrpc.protocol.StreamingRpcProto.internal_static_jrpc_Feedback_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sjt.jrpc.protocol.StreamingRpcProto.internal_static_jrpc_Feedback_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sjt.jrpc.protocol.StreamingRpcProto.Feedback.class, com.sjt.jrpc.protocol.StreamingRpcProto.Feedback.Builder.class);
    }

    public static final int CONSUMED_SIZE_FIELD_NUMBER = 1;
    private long consumedSize_;
    /**
     * <code>int64 consumed_size = 1;</code>
     * @return The consumedSize.
     */
    public long getConsumedSize() {
      return consumedSize_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (consumedSize_ != 0L) {
        output.writeInt64(1, consumedSize_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (consumedSize_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, consumedSize_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.sjt.jrpc.protocol.StreamingRpcProto.Feedback)) {
        return super.equals(obj);
      }
      com.sjt.jrpc.protocol.StreamingRpcProto.Feedback other = (com.sjt.jrpc.protocol.StreamingRpcProto.Feedback) obj;

      if (getConsumedSize()
          != other.getConsumedSize()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CONSUMED_SIZE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getConsumedSize());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.sjt.jrpc.protocol.StreamingRpcProto.Feedback parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sjt.jrpc.protocol.StreamingRpcProto.Feedback parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sjt.jrpc.protocol.StreamingRpcProto.Feedback parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sjt.jrpc.protocol.StreamingRpcProto.Feedback parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sjt.jrpc.protocol.StreamingRpcProto.Feedback parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sjt.jrpc.protocol.StreamingRpcProto.Feedback parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sjt.jrpc.protocol.StreamingRpcProto.Feedback parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sjt.jrpc.protocol.StreamingRpcProto.Feedback parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sjt.jrpc.protocol.StreamingRpcProto.Feedback parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.sjt.jrpc.protocol.StreamingRpcProto.Feedback parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sjt.jrpc.protocol.StreamingRpcProto.Feedback parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sjt.jrpc.protocol.StreamingRpcProto.Feedback parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.sjt.jrpc.protocol.StreamingRpcProto.Feedback prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code jrpc.Feedback}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:jrpc.Feedback)
        com.sjt.jrpc.protocol.StreamingRpcProto.FeedbackOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sjt.jrpc.protocol.StreamingRpcProto.internal_static_jrpc_Feedback_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sjt.jrpc.protocol.StreamingRpcProto.internal_static_jrpc_Feedback_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sjt.jrpc.protocol.StreamingRpcProto.Feedback.class, com.sjt.jrpc.protocol.StreamingRpcProto.Feedback.Builder.class);
      }

      // Construct using com.sjt.jrpc.protocol.StreamingRpcProto.Feedback.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        consumedSize_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sjt.jrpc.protocol.StreamingRpcProto.internal_static_jrpc_Feedback_descriptor;
      }

      @java.lang.Override
      public com.sjt.jrpc.protocol.StreamingRpcProto.Feedback getDefaultInstanceForType() {
        return com.sjt.jrpc.protocol.StreamingRpcProto.Feedback.getDefaultInstance();
      }

      @java.lang.Override
      public com.sjt.jrpc.protocol.StreamingRpcProto.Feedback build() {
        com.sjt.jrpc.protocol.StreamingRpcProto.Feedback result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.sjt.jrpc.protocol.StreamingRpcProto.Feedback buildPartial() {
        com.sjt.jrpc.protocol.StreamingRpcProto.Feedback result = new com.sjt.jrpc.protocol.StreamingRpcProto.Feedback(this);
        result.consumedSize_ = consumedSize_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sjt.jrpc.protocol.StreamingRpcProto.Feedback) {
          return mergeFrom((com.sjt.jrpc.protocol.StreamingRpcProto.Feedback)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sjt.jrpc.protocol.StreamingRpcProto.Feedback other) {
        if (other == com.sjt.jrpc.protocol.StreamingRpcProto.Feedback.getDefaultInstance()) return this;
        if (other.getConsumedSize() != 0L) {
          setConsumedSize(other.getConsumedSize());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sjt.jrpc.protocol.StreamingRpcProto.Feedback parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.sjt.jrpc.protocol.StreamingRpcProto.Feedback) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long consumedSize_ ;
      /**
       * <code>int64 consumed_size = 1;</code>
       * @return The consumedSize.
       */
      public long getConsumedSize() {
        return consumedSize_;
      }
      /**
       * <code>int64 consumed_size = 1;</code>
       * @param value The consumedSize to set.
       * @return This builder for chaining.
       */
      public Builder setConsumedSize(long value) {
        
        consumedSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 consumed_size = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearConsumedSize() {
        
        consumedSize_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:jrpc.Feedback)
    }

    // @@protoc_insertion_point(class_scope:jrpc.Feedback)
    private static final com.sjt.jrpc.protocol.StreamingRpcProto.Feedback DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.sjt.jrpc.protocol.StreamingRpcProto.Feedback();
    }

    public static com.sjt.jrpc.protocol.StreamingRpcProto.Feedback getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Feedback>
        PARSER = new com.google.protobuf.AbstractParser<Feedback>() {
      @java.lang.Override
      public Feedback parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Feedback(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Feedback> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Feedback> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.sjt.jrpc.protocol.StreamingRpcProto.Feedback getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jrpc_StreamSettings_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jrpc_StreamSettings_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jrpc_StreamFrameMeta_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jrpc_StreamFrameMeta_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_jrpc_Feedback_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_jrpc_Feedback_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030streaming_rpc_meta.proto\022\004jrpc\"L\n\016Stre" +
      "amSettings\022\021\n\tstream_id\030\001 \001(\003\022\025\n\rneed_fe" +
      "edback\030\002 \001(\010\022\020\n\010writable\030\003 \001(\010\"\237\001\n\017Strea" +
      "mFrameMeta\022\021\n\tstream_id\030\001 \001(\003\022\030\n\020source_" +
      "stream_id\030\002 \001(\003\022#\n\nframe_type\030\003 \001(\0162\017.jr" +
      "pc.FrameType\022\030\n\020has_continuation\030\004 \001(\010\022 " +
      "\n\010feedback\030\005 \001(\0132\016.jrpc.Feedback\"!\n\010Feed" +
      "back\022\025\n\rconsumed_size\030\001 \001(\003*{\n\tFrameType" +
      "\022\026\n\022FRAME_TYPE_UNKNOWN\020\000\022\022\n\016FRAME_TYPE_R" +
      "ST\020\001\022\024\n\020FRAME_TYPE_CLOSE\020\002\022\023\n\017FRAME_TYPE" +
      "_DATA\020\003\022\027\n\023FRAME_TYPE_FEEDBACK\020\004B*\n\025com." +
      "sjt.jrpc.protocolB\021StreamingRpcProtob\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_jrpc_StreamSettings_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_jrpc_StreamSettings_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jrpc_StreamSettings_descriptor,
        new java.lang.String[] { "StreamId", "NeedFeedback", "Writable", });
    internal_static_jrpc_StreamFrameMeta_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_jrpc_StreamFrameMeta_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jrpc_StreamFrameMeta_descriptor,
        new java.lang.String[] { "StreamId", "SourceStreamId", "FrameType", "HasContinuation", "Feedback", });
    internal_static_jrpc_Feedback_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_jrpc_Feedback_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_jrpc_Feedback_descriptor,
        new java.lang.String[] { "ConsumedSize", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
